config/routes.rb
Friendsatsnow::Application.routes.draw do

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  resources :participants, only: [:new, :create, :show]

  root to:'pages#home'

  

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me

  after_create { |admin| admin.send_reset_password_instructions }
 
  def password_required?
    new_record? ? false : super
  end
end

app/models/participant.rb
class Participant < ActiveRecord::Base
  attr_accessible :name, :surname, :email, :payment_date, :payment_confirmed

  validates :name, :surname, :email, presence: true
  validates :email, uniqueness: true, on: :create
  validates :email, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i, on: :create}

  def paid?
    not self.payment_date.nil?
  end

  def confirm_payment
    self.payment_date ||= Time.now
    self.payment_confirmed = true
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
    reset_session
    respond_to do |format|
      format.html
      format.js
    end
  end
  
end

app/controllers/participants_controller.rb
class ParticipantsController < ApplicationController

  # GET /participants/new
  def new
    @participant = Participant.new

    respond_to do |format|
      format.js
    end
  end

  # POST /participants
  def create
    @participant = Participant.new(params[:participant])

    respond_to do |format|
      if @participant.save
        ConfirmationMailer.confirm_signup(@participant).deliver
        format.js { redirect_to @participant }
      else
        format.js { render action: "new" }
      end
      b = []
      b.to_enum
    end
  end

  # GET /participants/id
  def show
    @participant = Participant.find(params[:id])

    respond_to do |format|
      format.js
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/participants_helper.rb
module ParticipantsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Friendsatsnow</title>
  <%= stylesheet_link_tag "screen", media: 'screen, projection' %>
  <%= stylesheet_link_tag "print", media: 'print' %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <!--[if lt IE 8]>
  <%= stylesheet_link_tag "ie", media: 'screen, projection' %>
  <![endif]-->
  <link href='http://fonts.googleapis.com/css?family=Delius' rel='stylesheet' type='text/css'>
</head>
<body>

  <div class="container">
    <div id="header">
      <%= link_to image_tag("logo2012.png", :border=>0), :controller => 'pages', :action => 'home' %>
    </div>
    <div id="content">
      <%= yield %>
    </div>
  </div>
</body>
</html>

app/views/pages/_maintext.html.erb
<h2>Friends@Snow ist leider schon vorbei!</h2>
<div id="text">
<p>
Zurzeit ist kein Friends@Snow-Event geplant. Du kannst dich aber trotzdem eintragen,
einfach so zum Spass.. Das ist ja auch nur eine Demo-Installation. Aber wer weiss,
vielleicht gibts Friends@Snow bald auch wieder in echt.</p>
<p>Letztes Jahr waren wir auf der kleinen Scheidegg im Restaurant
<a href="http://www.grindelwaldblick.ch/" target="blank" >Grindelwaldblick</a>. Das nächste
Mal geht's dann vielleicht nach Zermatt.
</div>
<p id="navlink">Jetzt gleich <%= link_to "anmelden", new_participant_path, remote: true %></p>

app/views/pages/home.html.erb
<%= render "maintext" %>

app/views/participants/_form.html.erb
<%= form_for(@participant, remote: true) do |f| %>
  <div class="error_explanation">
  <% if @participant.errors.any? %>
    <%= raw @participant.errors.full_messages[0] %>
  <% end %>
  </div>
  <div class="field">
    <%= f.label :name %> 
    <%= f.text_field :name %>
  </div>
   <div class="field">
    <%= f.label :surname %> 
    <%= f.text_field :surname %>
  </div>
  <div class="field">
    <%= f.label :email %> 
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit t('.submit'), :disable_with => 'Anmelden' %>
  </div>
<% end %>